# Generated by Django 5.1.6 on 2025-02-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'db_table': 'Size',
            },
        ),
        migrations.CreateModel(
            name='Skateboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.CharField(max_length=255, verbose_name='Описание товара')),
                ('img', models.ImageField(upload_to='skateboards/', verbose_name='Изображение товара')),
                ('img_lots', models.ImageField(upload_to='skateboards/', verbose_name='Много картинок')),
                ('price_discount', models.CharField(max_length=255, verbose_name='Цена со скидкой')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Skateboards', to='test_site.brand', verbose_name='Бренды')),
                ('color_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Skateboards', to='test_site.color', verbose_name='Цвета')),
                ('size_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Skateboards', to='test_site.size', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Скейтборд',
                'verbose_name_plural': 'Скейтборды',
                'db_table': 'skateboards',
            },
        ),
    ]
