# Generated by Django 5.1.6 on 2025-02-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skateboards',
            table='Skateboards',
        ),
    ]
