# Generated by Django 5.1.6 on 2025-02-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0002_alter_skateboards_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateboards',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='skateboards',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Скидка (%)'),
        ),
    ]
