# Generated by Django 5.1.6 on 2025-02-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0004_alter_skateboards_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateboards',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Скидка (%)'),
        ),
    ]
