# Generated by Django 5.1.6 on 2025-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0005_alter_skateboards_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateboards',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
