# Generated by Django 5.1.6 on 2025-02-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0012_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.CharField(max_length=255, verbose_name='Описание товара')),
                ('img', models.ImageField(upload_to='shoes/', verbose_name='Изображение товара')),
                ('img_lots', models.ImageField(upload_to='shoes/', verbose_name='Много картинок')),
                ('price_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Скидка (%)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoes', to='test_site.brand', verbose_name='Бренды')),
                ('color_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoes', to='test_site.color', verbose_name='Цвета')),
                ('size_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoes', to='test_site.size', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
                'db_table': 'Shoes',
            },
        ),
    ]
