# Generated by Django 5.1.6 on 2025-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0014_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('img', models.ImageField(upload_to='accessories/', verbose_name='Изображение баннера')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'db_table': 'Banners',
            },
        ),
    ]
