# Generated by Django 5.1.6 on 2025-02-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0015_banners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цветов'},
        ),
    ]
