# Generated by Django 5.1.6 on 2025-02-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0016_alter_color_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name': 'Аксессуар', 'verbose_name_plural': 'Аксессуаров'},
        ),
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеров'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэндов'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежд'},
        ),
        migrations.AlterModelOptions(
            name='longboards',
            options={'verbose_name': 'Лонгборд', 'verbose_name_plural': 'Лонгбордов'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Обувь', 'verbose_name_plural': 'Обувей'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеров'},
        ),
        migrations.AlterModelOptions(
            name='skateboards',
            options={'verbose_name': 'Скейтборд', 'verbose_name_plural': 'Скейтбордов'},
        ),
        migrations.AlterModelOptions(
            name='skis',
            options={'verbose_name': 'Лыжи', 'verbose_name_plural': 'Лыж'},
        ),
        migrations.AlterModelOptions(
            name='snowboards',
            options={'verbose_name': 'Сноуборд', 'verbose_name_plural': 'Сноубордов'},
        ),
        migrations.AlterModelOptions(
            name='surfings',
            options={'verbose_name': 'Серфинг', 'verbose_name_plural': 'Серфингов'},
        ),
    ]
